### PR TITLE
Fix reference to non-existent variable

### PR DESCRIPTION
**Pull request by fwitzke**
Context: While trying to use `Quaderno::Base.ping`, I got this error:
```ruby
irb(main):001:0> Quaderno::Base.ping
NameError: undefined local variable or method `response' for Quaderno::Base:Class
Did you mean?  respond_to?
        from .../vendor/bundle/ruby/2.4.0/gems/quaderno-2.1.1/lib/quaderno-ruby/exceptions/exceptions.rb:57:in `check_exception_for'
```

Further digging into the code, it seems like this was a typo with the original implementation.

- Introduced by #24

### CODE REVIEW

**Comment by xxswingxx** [comment]
Many thanks for the PR

**Comment by xxswingxx** [comment]
The fix has already been published in the new 2.1.2 release. Thanks again!
